# Generated by Django 3.2.24 on 2024-02-19 06:58

from django.db import migrations, models
import firstCarSogang_signuplogin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('kakaotalkID', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('photo1', models.ImageField(null=True, upload_to=firstCarSogang_signuplogin.models.user_directory_path)),
                ('photo2', models.ImageField(null=True, upload_to=firstCarSogang_signuplogin.models.user_directory_path)),
                ('photo3', models.ImageField(null=True, upload_to=firstCarSogang_signuplogin.models.user_directory_path)),
                ('password', models.CharField(max_length=25)),
                ('train', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('otp', models.CharField(default='20249', max_length=5)),
                ('ticketCount', models.IntegerField(default=3)),
                ('useTicket', models.BooleanField(default=False)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
