# Generated by Django 5.0.1 on 2024-02-25 05:38

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AfterDay1Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(unique=True, verbose_name='질문 ID')),
                ('question', models.CharField(max_length=1000, verbose_name='질문1')),
                ('placeholder', models.CharField(max_length=1000)),
                ('multipleChoiceAnswer1', models.CharField(max_length=1000, verbose_name='객관식 답변1')),
                ('multipleChoiceAnswer2', models.CharField(max_length=1000, verbose_name='객관식 답변2')),
                ('multipleChoiceAnswer3', models.CharField(max_length=1000, verbose_name='객관식 답변3')),
                ('multipleChoiceAnswer4', models.CharField(max_length=1000, verbose_name='객관식 답변4')),
                ('multipleChoiceAnswer5', models.CharField(max_length=1000, verbose_name='객관식 답변5')),
                ('answer', models.CharField(blank=True, max_length=1000, null=True, verbose_name='주관식 답변')),
                ('answer2', models.IntegerField(default=1)),
                ('comments', models.ManyToManyField(related_name='after_day1_comments', to='firstCarSogang_tickets.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Day1Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000, verbose_name='질문')),
                ('placeholder', models.CharField(max_length=1000)),
                ('answer', models.CharField(blank=True, max_length=1000, null=True, verbose_name='대답')),
                ('comments', models.ManyToManyField(related_name='day1_comments', to='firstCarSogang_tickets.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_question', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketNumber', models.IntegerField(blank=True, null=True, verbose_name='티켓 번호')),
                ('progressingDay', models.IntegerField(verbose_name='진행중인 날짜')),
                ('isAnswered', models.BooleanField(default=False, verbose_name='답변 여부')),
                ('choose', models.BooleanField(default=False, verbose_name='선택 여부')),
                ('day_question', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, null=True, size=None)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='내 티켓 아이디')),
                ('withWhom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_with_whom', to=settings.AUTH_USER_MODEL, verbose_name='상대편 티켓 아이디')),
            ],
        ),
    ]
