# Generated by Django 5.0.1 on 2024-02-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstCarSogang_tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='day_question',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
